@url = http://localhost:3000
###
GET {{url}}/api/any_route

###

POST {{url}}/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "username": "johndoe"
}
###
@user_id = 8a741410-94cc-452f-9b17-4a27340b0029
###
GET {{url}}/api/users/{{user_id}}
###
PUT {{url}}/api/users/{{user_id}}
Content-Type: application/json

{
  "name": "John Doe Edited"
}
###
DELETE {{url}}/api/users/{{user_id}}
###
GET {{url}}/api/users?limit=5&offset=0
